title: [Graph Neural Network on 3D Points]
description: [This is the DSC180B B01Group04 project. This project aims to compare performance of GNN, PointNet, and GNN-PointNet on dataset ModelNet40 and ShapeNet]
theme: jekyll-theme-cayman